name: library

on: 
  schedule:
  #      - cron: 40 22 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set-environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: 
          pip install -r requirements.txt
        
        
    - name: run script
      run: python3 liu_old.py
